---
title: "Replication Paper"
author: "Alexandra Norris"
date: "4/14/2020"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```

## Abstract

This paper is a replication of the research conducted by Ejdemyr et al. (2017): "Segregation, Ethnic Favoritism, and the Strategic Targeting of Local Public Goods".  In this replication, I replicate the research using the code provided by the researchers and conduct an extension with the data to learn more about the issue. After assessing my own findings from the replication, I will conclude whether I think the results of the original paper seem like they make sense.


## Introduction

The paper by Ejdemyr et al. (2017) explores the issues of public goods provision and how ethnicity may play a role in how these goods are distributed.  In this paper, I use R to replicate the findings of Ejdemyr et al. (2017) and to conduct an extension in which I use the data to look deeper into the subject matter.

## Lit Review

This section of the paper is a literature reveiw of academic literature that is related to the subject matter of my replication.  The literature review in the original paper (Ejdemyr et al. 2017) contains many references to papers that are related to the research question and findings.

